# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RvAccountPreferenceAssoc',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('account_id', models.IntegerField()),
                ('preference_id', models.IntegerField()),
                ('value', models.TextField()),
            ],
            options={
                'db_table': 'rv_account_preference_assoc',
            },
        ),
        migrations.CreateModel(
            name='RvAccounts',
            fields=[
                ('account_id', models.AutoField(serialize=False, primary_key=True)),
                ('account_type', models.CharField(max_length=16)),
                ('account_name', models.CharField(max_length=255, null=True, blank=True)),
                ('m2m_password', models.CharField(max_length=32, null=True, blank=True)),
                ('m2m_ticket', models.CharField(max_length=32, null=True, blank=True)),
            ],
            options={
                'db_table': 'rv_accounts',
            },
        ),
        migrations.CreateModel(
            name='RvAccountUserAssoc',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('account_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('linked', models.DateTimeField(null=True, blank=True)),
            ],
            options={
                'db_table': 'rv_account_user_assoc',
            },
        ),
        migrations.CreateModel(
            name='RvAccountUserPermissionAssoc',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('account_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('permission_id', models.IntegerField()),
                ('is_allowed', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'rv_account_user_permission_assoc',
            },
        ),
        migrations.CreateModel(
            name='RvAcls',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('bannerid', models.IntegerField()),
                ('logical', models.CharField(max_length=3)),
                ('type', models.CharField(max_length=255)),
                ('comparison', models.CharField(max_length=2)),
                ('data', models.TextField()),
                ('executionorder', models.IntegerField()),
            ],
            options={
                'db_table': 'rv_acls',
            },
        ),
        migrations.CreateModel(
            name='RvAclsChannel',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('channelid', models.IntegerField()),
                ('logical', models.CharField(max_length=3)),
                ('type', models.CharField(max_length=255)),
                ('comparison', models.CharField(max_length=2)),
                ('data', models.TextField()),
                ('executionorder', models.IntegerField()),
            ],
            options={
                'db_table': 'rv_acls_channel',
            },
        ),
        migrations.CreateModel(
            name='RvAdCategoryAssoc',
            fields=[
                ('ad_category_assoc_id', models.AutoField(serialize=False, primary_key=True)),
                ('category_id', models.IntegerField()),
                ('ad_id', models.IntegerField()),
            ],
            options={
                'db_table': 'rv_ad_category_assoc',
            },
        ),
        migrations.CreateModel(
            name='RvAdZoneAssoc',
            fields=[
                ('ad_zone_assoc_id', models.AutoField(serialize=False, primary_key=True)),
                ('zone_id', models.IntegerField(null=True, blank=True)),
                ('ad_id', models.IntegerField(null=True, blank=True)),
                ('priority', models.FloatField(null=True, blank=True)),
                ('link_type', models.SmallIntegerField()),
                ('priority_factor', models.FloatField(null=True, blank=True)),
                ('to_be_delivered', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'rv_ad_zone_assoc',
            },
        ),
        migrations.CreateModel(
            name='RvAffiliates',
            fields=[
                ('affiliateid', models.AutoField(serialize=False, primary_key=True)),
                ('agencyid', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('mnemonic', models.CharField(max_length=5)),
                ('comments', models.TextField(null=True, blank=True)),
                ('contact', models.CharField(max_length=255, null=True, blank=True)),
                ('email', models.CharField(max_length=64)),
                ('website', models.CharField(max_length=255, null=True, blank=True)),
                ('updated', models.DateTimeField(null=True, blank=True)),
                ('an_website_id', models.IntegerField(null=True, blank=True)),
                ('oac_country_code', models.CharField(max_length=2)),
                ('oac_language_id', models.IntegerField(null=True, blank=True)),
                ('oac_category_id', models.IntegerField(null=True, blank=True)),
                ('as_website_id', models.IntegerField(null=True, blank=True)),
                ('account_id', models.IntegerField(unique=True, null=True, blank=True)),
            ],
            options={
                'db_table': 'rv_affiliates',
            },
        ),
        migrations.CreateModel(
            name='RvAffiliatesExtra',
            fields=[
                ('affiliateid', models.IntegerField(serialize=False, primary_key=True)),
                ('address', models.TextField(null=True, blank=True)),
                ('city', models.CharField(max_length=255, null=True, blank=True)),
                ('postcode', models.CharField(max_length=64, null=True, blank=True)),
                ('country', models.CharField(max_length=255, null=True, blank=True)),
                ('phone', models.CharField(max_length=64, null=True, blank=True)),
                ('fax', models.CharField(max_length=64, null=True, blank=True)),
                ('account_contact', models.CharField(max_length=255, null=True, blank=True)),
                ('payee_name', models.CharField(max_length=255, null=True, blank=True)),
                ('tax_id', models.CharField(max_length=64, null=True, blank=True)),
                ('mode_of_payment', models.CharField(max_length=64, null=True, blank=True)),
                ('currency', models.CharField(max_length=64, null=True, blank=True)),
                ('unique_users', models.IntegerField(null=True, blank=True)),
                ('unique_views', models.IntegerField(null=True, blank=True)),
                ('page_rank', models.IntegerField(null=True, blank=True)),
                ('category', models.CharField(max_length=255, null=True, blank=True)),
                ('help_file', models.CharField(max_length=255, null=True, blank=True)),
            ],
            options={
                'db_table': 'rv_affiliates_extra',
            },
        ),
        migrations.CreateModel(
            name='RvAgency',
            fields=[
                ('agencyid', models.AutoField(serialize=False, primary_key=True)),
                ('name', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=255, null=True, blank=True)),
                ('email', models.CharField(max_length=64)),
                ('logout_url', models.CharField(max_length=255, null=True, blank=True)),
                ('active', models.SmallIntegerField(null=True, blank=True)),
                ('updated', models.DateTimeField(null=True, blank=True)),
                ('account_id', models.IntegerField(unique=True, null=True, blank=True)),
            ],
            options={
                'db_table': 'rv_agency',
            },
        ),
        migrations.CreateModel(
            name='RvApplicationVariable',
            fields=[
                ('name', models.CharField(max_length=255, serialize=False, primary_key=True)),
                ('value', models.TextField()),
            ],
            options={
                'db_table': 'rv_application_variable',
            },
        ),
        migrations.CreateModel(
            name='RvAudit',
            fields=[
                ('auditid', models.AutoField(serialize=False, primary_key=True)),
                ('actionid', models.IntegerField()),
                ('context', models.CharField(max_length=255)),
                ('contextid', models.IntegerField(null=True, blank=True)),
                ('parentid', models.IntegerField(null=True, blank=True)),
                ('details', models.TextField()),
                ('userid', models.IntegerField()),
                ('username', models.CharField(max_length=64, null=True, blank=True)),
                ('usertype', models.SmallIntegerField()),
                ('updated', models.DateTimeField(null=True, blank=True)),
                ('account_id', models.IntegerField()),
                ('advertiser_account_id', models.IntegerField(null=True, blank=True)),
                ('website_account_id', models.IntegerField(null=True, blank=True)),
            ],
            options={
                'db_table': 'rv_audit',
            },
        ),
        migrations.CreateModel(
            name='RvBanners',
            fields=[
                ('bannerid', models.AutoField(serialize=False, primary_key=True)),
                ('campaignid', models.IntegerField()),
                ('contenttype', models.TextField()),
                ('pluginversion', models.IntegerField()),
                ('storagetype', models.TextField()),
                ('filename', models.CharField(max_length=255)),
                ('imageurl', models.CharField(max_length=255)),
                ('htmltemplate', models.TextField()),
                ('htmlcache', models.TextField()),
                ('width', models.SmallIntegerField()),
                ('height', models.SmallIntegerField()),
                ('weight', models.SmallIntegerField()),
                ('seq', models.SmallIntegerField()),
                ('target', models.CharField(max_length=16)),
                ('url', models.TextField()),
                ('alt', models.CharField(max_length=255)),
                ('statustext', models.CharField(max_length=255)),
                ('bannertext', models.TextField()),
                ('description', models.CharField(max_length=255)),
                ('adserver', models.CharField(max_length=255)),
                ('block', models.IntegerField()),
                ('capping', models.IntegerField()),
                ('session_capping', models.IntegerField()),
                ('compiledlimitation', models.TextField()),
                ('acl_plugins', models.TextField(null=True, blank=True)),
                ('append', models.TextField()),
                ('bannertype', models.SmallIntegerField()),
                ('alt_filename', models.CharField(max_length=255)),
                ('alt_imageurl', models.CharField(max_length=255)),
                ('alt_contenttype', models.TextField()),
                ('comments', models.TextField(null=True, blank=True)),
                ('updated', models.DateTimeField(null=True, blank=True)),
                ('acls_updated', models.DateTimeField(null=True, blank=True)),
                ('keyword', models.CharField(max_length=255)),
                ('transparent', models.SmallIntegerField()),
                ('parameters', models.TextField(null=True, blank=True)),
                ('an_banner_id', models.IntegerField(null=True, blank=True)),
                ('as_banner_id', models.IntegerField(null=True, blank=True)),
                ('status', models.IntegerField()),
                ('ad_direct_status', models.SmallIntegerField()),
                ('ad_direct_rejection_reason_id', models.SmallIntegerField()),
                ('ext_bannertype', models.CharField(max_length=255, null=True, blank=True)),
                ('prepend', models.TextField()),
            ],
            options={
                'db_table': 'rv_banners',
            },
        ),
        migrations.CreateModel(
            name='RvCampaigns',
            fields=[
                ('campaignid', models.AutoField(serialize=False, primary_key=True)),
                ('campaignname', models.CharField(max_length=255)),
                ('clientid', models.IntegerField()),
                ('views', models.IntegerField(null=True, blank=True)),
                ('clicks', models.IntegerField(null=True, blank=True)),
                ('conversions', models.IntegerField(null=True, blank=True)),
                ('priority', models.IntegerField()),
                ('weight', models.SmallIntegerField()),
                ('target_impression', models.IntegerField()),
                ('target_click', models.IntegerField()),
                ('target_conversion', models.IntegerField()),
                ('anonymous', models.BooleanField()),
                ('companion', models.SmallIntegerField(null=True, blank=True)),
                ('comments', models.TextField(null=True, blank=True)),
                ('revenue', models.DecimalField(null=True, max_digits=10, decimal_places=4, blank=True)),
                ('revenue_type', models.SmallIntegerField(null=True, blank=True)),
                ('updated', models.DateTimeField(null=True, blank=True)),
                ('block', models.IntegerField()),
                ('capping', models.IntegerField()),
                ('session_capping', models.IntegerField()),
                ('an_campaign_id', models.IntegerField(null=True, blank=True)),
                ('as_campaign_id', models.IntegerField(null=True, blank=True)),
                ('status', models.IntegerField()),
                ('an_status', models.IntegerField()),
                ('as_reject_reason', models.IntegerField()),
                ('hosted_views', models.IntegerField()),
                ('hosted_clicks', models.IntegerField()),
                ('viewwindow', models.IntegerField()),
                ('clickwindow', models.IntegerField()),
                ('ecpm', models.DecimalField(null=True, max_digits=10, decimal_places=4, blank=True)),
                ('min_impressions', models.IntegerField()),
                ('ecpm_enabled', models.SmallIntegerField()),
                ('activate_time', models.DateTimeField(null=True, blank=True)),
                ('expire_time', models.DateTimeField(null=True, blank=True)),
                ('type', models.SmallIntegerField()),
                ('show_capped_no_cookie', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'rv_campaigns',
            },
        ),
        migrations.CreateModel(
            name='RvCampaignsTrackers',
            fields=[
                ('campaign_trackerid', models.AutoField(serialize=False, primary_key=True)),
                ('campaignid', models.IntegerField()),
                ('trackerid', models.IntegerField()),
                ('status', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'rv_campaigns_trackers',
            },
        ),
        migrations.CreateModel(
            name='RvCategory',
            fields=[
                ('category_id', models.AutoField(serialize=False, primary_key=True)),
                ('name', models.CharField(max_length=255, null=True, blank=True)),
            ],
            options={
                'db_table': 'rv_category',
            },
        ),
        migrations.CreateModel(
            name='RvChannel',
            fields=[
                ('channelid', models.AutoField(serialize=False, primary_key=True)),
                ('agencyid', models.IntegerField()),
                ('affiliateid', models.IntegerField()),
                ('name', models.CharField(max_length=255, null=True, blank=True)),
                ('description', models.CharField(max_length=255, null=True, blank=True)),
                ('compiledlimitation', models.TextField()),
                ('acl_plugins', models.TextField(null=True, blank=True)),
                ('active', models.SmallIntegerField(null=True, blank=True)),
                ('comments', models.TextField(null=True, blank=True)),
                ('updated', models.DateTimeField(null=True, blank=True)),
                ('acls_updated', models.DateTimeField(null=True, blank=True)),
            ],
            options={
                'db_table': 'rv_channel',
            },
        ),
        migrations.CreateModel(
            name='RvClients',
            fields=[
                ('clientid', models.AutoField(serialize=False, primary_key=True)),
                ('agencyid', models.IntegerField()),
                ('clientname', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=255, null=True, blank=True)),
                ('email', models.CharField(max_length=64)),
                ('report', models.BooleanField()),
                ('reportinterval', models.IntegerField()),
                ('reportlastdate', models.DateField(null=True, blank=True)),
                ('reportdeactivate', models.BooleanField()),
                ('comments', models.TextField(null=True, blank=True)),
                ('updated', models.DateTimeField(null=True, blank=True)),
                ('an_adnetwork_id', models.IntegerField(null=True, blank=True)),
                ('as_advertiser_id', models.IntegerField(null=True, blank=True)),
                ('account_id', models.IntegerField(unique=True, null=True, blank=True)),
                ('advertiser_limitation', models.SmallIntegerField()),
                ('type', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'rv_clients',
            },
        ),
        migrations.CreateModel(
            name='RvDatabaseAction',
            fields=[
                ('database_action_id', models.AutoField(serialize=False, primary_key=True)),
                ('upgrade_action_id', models.IntegerField(null=True, blank=True)),
                ('schema_name', models.CharField(max_length=64, null=True, blank=True)),
                ('version', models.IntegerField()),
                ('timing', models.IntegerField()),
                ('action', models.IntegerField()),
                ('info1', models.CharField(max_length=255, null=True, blank=True)),
                ('info2', models.CharField(max_length=255, null=True, blank=True)),
                ('tablename', models.CharField(max_length=64, null=True, blank=True)),
                ('tablename_backup', models.CharField(max_length=64, null=True, blank=True)),
                ('table_backup_schema', models.TextField(null=True, blank=True)),
                ('updated', models.DateTimeField(null=True, blank=True)),
            ],
            options={
                'db_table': 'rv_database_action',
            },
        ),
        migrations.CreateModel(
            name='RvDataIntermediateAd',
            fields=[
                ('data_intermediate_ad_id', models.BigIntegerField(serialize=False, primary_key=True)),
                ('date_time', models.DateTimeField(null=True, blank=True)),
                ('operation_interval', models.IntegerField()),
                ('operation_interval_id', models.IntegerField()),
                ('interval_start', models.DateTimeField(null=True, blank=True)),
                ('interval_end', models.DateTimeField(null=True, blank=True)),
                ('ad_id', models.IntegerField()),
                ('creative_id', models.IntegerField()),
                ('zone_id', models.IntegerField()),
                ('requests', models.IntegerField()),
                ('impressions', models.IntegerField()),
                ('clicks', models.IntegerField()),
                ('conversions', models.IntegerField()),
                ('total_basket_value', models.DecimalField(max_digits=10, decimal_places=4)),
                ('total_num_items', models.IntegerField()),
                ('updated', models.DateTimeField(null=True, blank=True)),
            ],
            options={
                'db_table': 'rv_data_intermediate_ad',
            },
        ),
        migrations.CreateModel(
            name='RvDataIntermediateAdConnection',
            fields=[
                ('data_intermediate_ad_connection_id', models.BigIntegerField(serialize=False, primary_key=True)),
                ('server_raw_ip', models.CharField(max_length=16)),
                ('server_raw_tracker_impression_id', models.BigIntegerField()),
                ('viewer_id', models.CharField(max_length=32, null=True, blank=True)),
                ('viewer_session_id', models.CharField(max_length=32, null=True, blank=True)),
                ('tracker_date_time', models.DateTimeField(null=True, blank=True)),
                ('connection_date_time', models.DateTimeField(null=True, blank=True)),
                ('tracker_id', models.IntegerField()),
                ('ad_id', models.IntegerField()),
                ('creative_id', models.IntegerField()),
                ('zone_id', models.IntegerField()),
                ('tracker_channel', models.CharField(max_length=255, null=True, blank=True)),
                ('connection_channel', models.CharField(max_length=255, null=True, blank=True)),
                ('tracker_channel_ids', models.CharField(max_length=64, null=True, blank=True)),
                ('connection_channel_ids', models.CharField(max_length=64, null=True, blank=True)),
                ('tracker_language', models.CharField(max_length=13, null=True, blank=True)),
                ('connection_language', models.CharField(max_length=13, null=True, blank=True)),
                ('tracker_ip_address', models.CharField(max_length=16, null=True, blank=True)),
                ('connection_ip_address', models.CharField(max_length=16, null=True, blank=True)),
                ('tracker_host_name', models.CharField(max_length=255, null=True, blank=True)),
                ('connection_host_name', models.CharField(max_length=255, null=True, blank=True)),
                ('tracker_country', models.CharField(max_length=2, null=True, blank=True)),
                ('connection_country', models.CharField(max_length=2, null=True, blank=True)),
                ('tracker_https', models.IntegerField(null=True, blank=True)),
                ('connection_https', models.IntegerField(null=True, blank=True)),
                ('tracker_domain', models.CharField(max_length=255, null=True, blank=True)),
                ('connection_domain', models.CharField(max_length=255, null=True, blank=True)),
                ('tracker_page', models.CharField(max_length=255, null=True, blank=True)),
                ('connection_page', models.CharField(max_length=255, null=True, blank=True)),
                ('tracker_query', models.CharField(max_length=255, null=True, blank=True)),
                ('connection_query', models.CharField(max_length=255, null=True, blank=True)),
                ('tracker_referer', models.CharField(max_length=255, null=True, blank=True)),
                ('connection_referer', models.CharField(max_length=255, null=True, blank=True)),
                ('tracker_search_term', models.CharField(max_length=255, null=True, blank=True)),
                ('connection_search_term', models.CharField(max_length=255, null=True, blank=True)),
                ('tracker_user_agent', models.CharField(max_length=255, null=True, blank=True)),
                ('connection_user_agent', models.CharField(max_length=255, null=True, blank=True)),
                ('tracker_os', models.CharField(max_length=32, null=True, blank=True)),
                ('connection_os', models.CharField(max_length=32, null=True, blank=True)),
                ('tracker_browser', models.CharField(max_length=32, null=True, blank=True)),
                ('connection_browser', models.CharField(max_length=32, null=True, blank=True)),
                ('connection_action', models.IntegerField(null=True, blank=True)),
                ('connection_window', models.IntegerField(null=True, blank=True)),
                ('connection_status', models.IntegerField()),
                ('inside_window', models.SmallIntegerField()),
                ('comments', models.TextField(null=True, blank=True)),
                ('updated', models.DateTimeField(null=True, blank=True)),
            ],
            options={
                'db_table': 'rv_data_intermediate_ad_connection',
            },
        ),
        migrations.CreateModel(
            name='RvDataIntermediateAdVariableValue',
            fields=[
                ('data_intermediate_ad_variable_value_id', models.BigIntegerField(serialize=False, primary_key=True)),
                ('data_intermediate_ad_connection_id', models.BigIntegerField()),
                ('tracker_variable_id', models.IntegerField()),
                ('value', models.CharField(max_length=50, null=True, blank=True)),
            ],
            options={
                'db_table': 'rv_data_intermediate_ad_variable_value',
            },
        ),
        migrations.CreateModel(
            name='RvDataRawAdClick',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('viewer_id', models.CharField(max_length=32, null=True, blank=True)),
                ('viewer_session_id', models.CharField(max_length=32, null=True, blank=True)),
                ('date_time', models.DateTimeField(null=True, blank=True)),
                ('ad_id', models.IntegerField()),
                ('creative_id', models.IntegerField()),
                ('zone_id', models.IntegerField()),
                ('channel', models.CharField(max_length=255, null=True, blank=True)),
                ('channel_ids', models.CharField(max_length=64, null=True, blank=True)),
                ('language', models.CharField(max_length=32, null=True, blank=True)),
                ('ip_address', models.CharField(max_length=16, null=True, blank=True)),
                ('host_name', models.CharField(max_length=255, null=True, blank=True)),
                ('country', models.CharField(max_length=2, null=True, blank=True)),
                ('https', models.SmallIntegerField(null=True, blank=True)),
                ('domain', models.CharField(max_length=255, null=True, blank=True)),
                ('page', models.CharField(max_length=255, null=True, blank=True)),
                ('query', models.CharField(max_length=255, null=True, blank=True)),
                ('referer', models.CharField(max_length=255, null=True, blank=True)),
                ('search_term', models.CharField(max_length=255, null=True, blank=True)),
                ('user_agent', models.CharField(max_length=255, null=True, blank=True)),
                ('os', models.CharField(max_length=32, null=True, blank=True)),
                ('browser', models.CharField(max_length=32, null=True, blank=True)),
                ('max_https', models.SmallIntegerField(null=True, blank=True)),
                ('geo_region', models.CharField(max_length=50, null=True, blank=True)),
                ('geo_city', models.CharField(max_length=50, null=True, blank=True)),
                ('geo_postal_code', models.CharField(max_length=10, null=True, blank=True)),
                ('geo_latitude', models.DecimalField(null=True, max_digits=8, decimal_places=4, blank=True)),
                ('geo_longitude', models.DecimalField(null=True, max_digits=8, decimal_places=4, blank=True)),
                ('geo_dma_code', models.CharField(max_length=50, null=True, blank=True)),
                ('geo_area_code', models.CharField(max_length=50, null=True, blank=True)),
                ('geo_organisation', models.CharField(max_length=50, null=True, blank=True)),
                ('geo_netspeed', models.CharField(max_length=20, null=True, blank=True)),
                ('geo_continent', models.CharField(max_length=13, null=True, blank=True)),
            ],
            options={
                'db_table': 'rv_data_raw_ad_click',
            },
        ),
        migrations.CreateModel(
            name='RvDataRawAdImpression',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('viewer_id', models.CharField(max_length=32, null=True, blank=True)),
                ('viewer_session_id', models.CharField(max_length=32, null=True, blank=True)),
                ('date_time', models.DateTimeField(null=True, blank=True)),
                ('ad_id', models.IntegerField()),
                ('creative_id', models.IntegerField()),
                ('zone_id', models.IntegerField()),
                ('channel', models.CharField(max_length=255, null=True, blank=True)),
                ('channel_ids', models.CharField(max_length=64, null=True, blank=True)),
                ('language', models.CharField(max_length=32, null=True, blank=True)),
                ('ip_address', models.CharField(max_length=16, null=True, blank=True)),
                ('host_name', models.CharField(max_length=255, null=True, blank=True)),
                ('country', models.CharField(max_length=2, null=True, blank=True)),
                ('https', models.SmallIntegerField(null=True, blank=True)),
                ('domain', models.CharField(max_length=255, null=True, blank=True)),
                ('page', models.CharField(max_length=255, null=True, blank=True)),
                ('query', models.CharField(max_length=255, null=True, blank=True)),
                ('referer', models.CharField(max_length=255, null=True, blank=True)),
                ('search_term', models.CharField(max_length=255, null=True, blank=True)),
                ('user_agent', models.CharField(max_length=255, null=True, blank=True)),
                ('os', models.CharField(max_length=32, null=True, blank=True)),
                ('browser', models.CharField(max_length=32, null=True, blank=True)),
                ('max_https', models.SmallIntegerField(null=True, blank=True)),
                ('geo_region', models.CharField(max_length=50, null=True, blank=True)),
                ('geo_city', models.CharField(max_length=50, null=True, blank=True)),
                ('geo_postal_code', models.CharField(max_length=10, null=True, blank=True)),
                ('geo_latitude', models.DecimalField(null=True, max_digits=8, decimal_places=4, blank=True)),
                ('geo_longitude', models.DecimalField(null=True, max_digits=8, decimal_places=4, blank=True)),
                ('geo_dma_code', models.CharField(max_length=50, null=True, blank=True)),
                ('geo_area_code', models.CharField(max_length=50, null=True, blank=True)),
                ('geo_organisation', models.CharField(max_length=50, null=True, blank=True)),
                ('geo_netspeed', models.CharField(max_length=20, null=True, blank=True)),
                ('geo_continent', models.CharField(max_length=13, null=True, blank=True)),
            ],
            options={
                'db_table': 'rv_data_raw_ad_impression',
            },
        ),
        migrations.CreateModel(
            name='RvDataRawAdRequest',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('viewer_id', models.CharField(max_length=32, null=True, blank=True)),
                ('viewer_session_id', models.CharField(max_length=32, null=True, blank=True)),
                ('date_time', models.DateTimeField(null=True, blank=True)),
                ('ad_id', models.IntegerField()),
                ('creative_id', models.IntegerField()),
                ('zone_id', models.IntegerField()),
                ('channel', models.CharField(max_length=255, null=True, blank=True)),
                ('channel_ids', models.CharField(max_length=64, null=True, blank=True)),
                ('language', models.CharField(max_length=32, null=True, blank=True)),
                ('ip_address', models.CharField(max_length=16, null=True, blank=True)),
                ('host_name', models.CharField(max_length=255, null=True, blank=True)),
                ('https', models.SmallIntegerField(null=True, blank=True)),
                ('domain', models.CharField(max_length=255, null=True, blank=True)),
                ('page', models.CharField(max_length=255, null=True, blank=True)),
                ('query', models.CharField(max_length=255, null=True, blank=True)),
                ('referer', models.CharField(max_length=255, null=True, blank=True)),
                ('search_term', models.CharField(max_length=255, null=True, blank=True)),
                ('user_agent', models.CharField(max_length=255, null=True, blank=True)),
                ('os', models.CharField(max_length=32, null=True, blank=True)),
                ('browser', models.CharField(max_length=32, null=True, blank=True)),
                ('max_https', models.SmallIntegerField(null=True, blank=True)),
            ],
            options={
                'db_table': 'rv_data_raw_ad_request',
            },
        ),
        migrations.CreateModel(
            name='RvDataRawTrackerImpression',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('server_raw_tracker_impression_id', models.BigIntegerField()),
                ('server_raw_ip', models.CharField(max_length=16)),
                ('viewer_id', models.CharField(max_length=32)),
                ('viewer_session_id', models.CharField(max_length=32, null=True, blank=True)),
                ('date_time', models.DateTimeField(null=True, blank=True)),
                ('tracker_id', models.IntegerField()),
                ('channel', models.CharField(max_length=255, null=True, blank=True)),
                ('channel_ids', models.CharField(max_length=64, null=True, blank=True)),
                ('language', models.CharField(max_length=32, null=True, blank=True)),
                ('ip_address', models.CharField(max_length=16, null=True, blank=True)),
                ('host_name', models.CharField(max_length=255, null=True, blank=True)),
                ('country', models.CharField(max_length=2, null=True, blank=True)),
                ('https', models.IntegerField(null=True, blank=True)),
                ('domain', models.CharField(max_length=255, null=True, blank=True)),
                ('page', models.CharField(max_length=255, null=True, blank=True)),
                ('query', models.CharField(max_length=255, null=True, blank=True)),
                ('referer', models.CharField(max_length=255, null=True, blank=True)),
                ('search_term', models.CharField(max_length=255, null=True, blank=True)),
                ('user_agent', models.CharField(max_length=255, null=True, blank=True)),
                ('os', models.CharField(max_length=32, null=True, blank=True)),
                ('browser', models.CharField(max_length=32, null=True, blank=True)),
                ('max_https', models.IntegerField(null=True, blank=True)),
                ('geo_region', models.CharField(max_length=50, null=True, blank=True)),
                ('geo_city', models.CharField(max_length=50, null=True, blank=True)),
                ('geo_postal_code', models.CharField(max_length=10, null=True, blank=True)),
                ('geo_latitude', models.DecimalField(null=True, max_digits=8, decimal_places=4, blank=True)),
                ('geo_longitude', models.DecimalField(null=True, max_digits=8, decimal_places=4, blank=True)),
                ('geo_dma_code', models.CharField(max_length=50, null=True, blank=True)),
                ('geo_area_code', models.CharField(max_length=50, null=True, blank=True)),
                ('geo_organisation', models.CharField(max_length=50, null=True, blank=True)),
                ('geo_netspeed', models.CharField(max_length=20, null=True, blank=True)),
                ('geo_continent', models.CharField(max_length=13, null=True, blank=True)),
            ],
            options={
                'db_table': 'rv_data_raw_tracker_impression',
            },
        ),
        migrations.CreateModel(
            name='RvDataRawTrackerVariableValue',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('server_raw_tracker_impression_id', models.BigIntegerField()),
                ('server_raw_ip', models.CharField(max_length=16)),
                ('tracker_variable_id', models.IntegerField()),
                ('date_time', models.DateTimeField(null=True, blank=True)),
                ('value', models.CharField(max_length=50, null=True, blank=True)),
            ],
            options={
                'db_table': 'rv_data_raw_tracker_variable_value',
            },
        ),
        migrations.CreateModel(
            name='RvDataSummaryAdHourly',
            fields=[
                ('data_summary_ad_hourly_id', models.BigIntegerField(serialize=False, primary_key=True)),
                ('date_time', models.DateTimeField(null=True, blank=True)),
                ('ad_id', models.IntegerField()),
                ('creative_id', models.IntegerField()),
                ('zone_id', models.IntegerField()),
                ('requests', models.IntegerField()),
                ('impressions', models.IntegerField()),
                ('clicks', models.IntegerField()),
                ('conversions', models.IntegerField()),
                ('total_basket_value', models.DecimalField(null=True, max_digits=10, decimal_places=4, blank=True)),
                ('total_num_items', models.IntegerField(null=True, blank=True)),
                ('total_revenue', models.DecimalField(null=True, max_digits=10, decimal_places=4, blank=True)),
                ('total_cost', models.DecimalField(null=True, max_digits=10, decimal_places=4, blank=True)),
                ('total_techcost', models.DecimalField(null=True, max_digits=10, decimal_places=4, blank=True)),
                ('updated', models.DateTimeField(null=True, blank=True)),
            ],
            options={
                'db_table': 'rv_data_summary_ad_hourly',
            },
        ),
        migrations.CreateModel(
            name='RvDataSummaryAdZoneAssoc',
            fields=[
                ('data_summary_ad_zone_assoc_id', models.BigIntegerField(serialize=False, primary_key=True)),
                ('operation_interval', models.IntegerField()),
                ('operation_interval_id', models.IntegerField()),
                ('interval_start', models.DateTimeField(null=True, blank=True)),
                ('interval_end', models.DateTimeField(null=True, blank=True)),
                ('ad_id', models.IntegerField()),
                ('zone_id', models.IntegerField()),
                ('required_impressions', models.IntegerField()),
                ('requested_impressions', models.IntegerField()),
                ('priority', models.FloatField()),
                ('priority_factor', models.FloatField(null=True, blank=True)),
                ('priority_factor_limited', models.SmallIntegerField()),
                ('past_zone_traffic_fraction', models.FloatField(null=True, blank=True)),
                ('created', models.DateTimeField(null=True, blank=True)),
                ('created_by', models.IntegerField()),
                ('expired', models.DateTimeField(null=True, blank=True)),
                ('expired_by', models.IntegerField(null=True, blank=True)),
                ('to_be_delivered', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'rv_data_summary_ad_zone_assoc',
            },
        ),
        migrations.CreateModel(
            name='RvDataSummaryChannelDaily',
            fields=[
                ('data_summary_channel_daily_id', models.BigIntegerField(serialize=False, primary_key=True)),
                ('day', models.DateField(null=True, blank=True)),
                ('channel_id', models.IntegerField()),
                ('zone_id', models.IntegerField()),
                ('forecast_impressions', models.IntegerField()),
                ('actual_impressions', models.IntegerField()),
            ],
            options={
                'db_table': 'rv_data_summary_channel_daily',
            },
        ),
        migrations.CreateModel(
            name='RvDataSummaryZoneImpressionHistory',
            fields=[
                ('data_summary_zone_impression_history_id', models.BigIntegerField(serialize=False, primary_key=True)),
                ('operation_interval', models.IntegerField()),
                ('operation_interval_id', models.IntegerField()),
                ('interval_start', models.DateTimeField(null=True, blank=True)),
                ('interval_end', models.DateTimeField(null=True, blank=True)),
                ('zone_id', models.IntegerField()),
                ('forecast_impressions', models.IntegerField(null=True, blank=True)),
                ('actual_impressions', models.IntegerField(null=True, blank=True)),
                ('est', models.SmallIntegerField(null=True, blank=True)),
            ],
            options={
                'db_table': 'rv_data_summary_zone_impression_history',
            },
        ),
        migrations.CreateModel(
            name='RvImages',
            fields=[
                ('filename', models.CharField(max_length=128, serialize=False, primary_key=True)),
                ('contents', models.BinaryField()),
                ('t_stamp', models.DateTimeField(null=True, blank=True)),
            ],
            options={
                'db_table': 'rv_images',
            },
        ),
        migrations.CreateModel(
            name='RvLogMaintenanceForecasting',
            fields=[
                ('log_maintenance_forecasting_id', models.AutoField(serialize=False, primary_key=True)),
                ('start_run', models.DateTimeField(null=True, blank=True)),
                ('end_run', models.DateTimeField(null=True, blank=True)),
                ('operation_interval', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('updated_to', models.DateTimeField(null=True, blank=True)),
            ],
            options={
                'db_table': 'rv_log_maintenance_forecasting',
            },
        ),
        migrations.CreateModel(
            name='RvLogMaintenancePriority',
            fields=[
                ('log_maintenance_priority_id', models.AutoField(serialize=False, primary_key=True)),
                ('start_run', models.DateTimeField(null=True, blank=True)),
                ('end_run', models.DateTimeField(null=True, blank=True)),
                ('operation_interval', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('run_type', models.SmallIntegerField()),
                ('updated_to', models.DateTimeField(null=True, blank=True)),
            ],
            options={
                'db_table': 'rv_log_maintenance_priority',
            },
        ),
        migrations.CreateModel(
            name='RvLogMaintenanceStatistics',
            fields=[
                ('log_maintenance_statistics_id', models.AutoField(serialize=False, primary_key=True)),
                ('start_run', models.DateTimeField(null=True, blank=True)),
                ('end_run', models.DateTimeField(null=True, blank=True)),
                ('duration', models.IntegerField()),
                ('adserver_run_type', models.IntegerField(null=True, blank=True)),
                ('search_run_type', models.IntegerField(null=True, blank=True)),
                ('tracker_run_type', models.IntegerField(null=True, blank=True)),
                ('updated_to', models.DateTimeField(null=True, blank=True)),
            ],
            options={
                'db_table': 'rv_log_maintenance_statistics',
            },
        ),
        migrations.CreateModel(
            name='RvPasswordRecovery',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('user_type', models.CharField(max_length=64)),
                ('user_id', models.IntegerField()),
                ('recovery_id', models.CharField(unique=True, max_length=64)),
                ('updated', models.DateTimeField(null=True, blank=True)),
            ],
            options={
                'db_table': 'rv_password_recovery',
            },
        ),
        migrations.CreateModel(
            name='RvPlacementZoneAssoc',
            fields=[
                ('placement_zone_assoc_id', models.AutoField(serialize=False, primary_key=True)),
                ('zone_id', models.IntegerField(null=True, blank=True)),
                ('placement_id', models.IntegerField(null=True, blank=True)),
            ],
            options={
                'db_table': 'rv_placement_zone_assoc',
            },
        ),
        migrations.CreateModel(
            name='RvPreferences',
            fields=[
                ('preference_id', models.AutoField(serialize=False, primary_key=True)),
                ('preference_name', models.CharField(unique=True, max_length=64)),
                ('account_type', models.CharField(max_length=16)),
            ],
            options={
                'db_table': 'rv_preferences',
            },
        ),
        migrations.CreateModel(
            name='RvSession',
            fields=[
                ('sessionid', models.CharField(max_length=32, serialize=False, primary_key=True)),
                ('sessiondata', models.TextField()),
                ('lastused', models.DateTimeField(null=True, blank=True)),
            ],
            options={
                'db_table': 'rv_session',
            },
        ),
        migrations.CreateModel(
            name='RvTargetstats',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('day', models.DateField(null=True, blank=True)),
                ('campaignid', models.IntegerField()),
                ('target', models.IntegerField()),
                ('views', models.IntegerField()),
                ('modified', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'rv_targetstats',
            },
        ),
        migrations.CreateModel(
            name='RvTrackerAppend',
            fields=[
                ('tracker_append_id', models.AutoField(serialize=False, primary_key=True)),
                ('tracker_id', models.IntegerField()),
                ('rank', models.IntegerField()),
                ('tagcode', models.TextField()),
                ('paused', models.BooleanField()),
                ('autotrack', models.BooleanField()),
            ],
            options={
                'db_table': 'rv_tracker_append',
            },
        ),
        migrations.CreateModel(
            name='RvTrackers',
            fields=[
                ('trackerid', models.AutoField(serialize=False, primary_key=True)),
                ('trackername', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('clientid', models.IntegerField()),
                ('viewwindow', models.IntegerField()),
                ('clickwindow', models.IntegerField()),
                ('blockwindow', models.IntegerField()),
                ('status', models.SmallIntegerField()),
                ('type', models.SmallIntegerField()),
                ('linkcampaigns', models.BooleanField()),
                ('variablemethod', models.TextField()),
                ('appendcode', models.TextField()),
                ('updated', models.DateTimeField(null=True, blank=True)),
            ],
            options={
                'db_table': 'rv_trackers',
            },
        ),
        migrations.CreateModel(
            name='RvUpgradeAction',
            fields=[
                ('upgrade_action_id', models.AutoField(serialize=False, primary_key=True)),
                ('upgrade_name', models.CharField(max_length=128, null=True, blank=True)),
                ('version_to', models.CharField(max_length=64)),
                ('version_from', models.CharField(max_length=64, null=True, blank=True)),
                ('action', models.IntegerField()),
                ('description', models.CharField(max_length=255, null=True, blank=True)),
                ('logfile', models.CharField(max_length=128, null=True, blank=True)),
                ('confbackup', models.CharField(max_length=128, null=True, blank=True)),
                ('updated', models.DateTimeField(null=True, blank=True)),
            ],
            options={
                'db_table': 'rv_upgrade_action',
            },
        ),
        migrations.CreateModel(
            name='RvUserlog',
            fields=[
                ('userlogid', models.AutoField(serialize=False, primary_key=True)),
                ('timestamp', models.IntegerField()),
                ('usertype', models.SmallIntegerField()),
                ('userid', models.IntegerField()),
                ('action', models.IntegerField()),
                ('object', models.IntegerField(null=True, blank=True)),
                ('details', models.TextField(null=True, blank=True)),
            ],
            options={
                'db_table': 'rv_userlog',
            },
        ),
        migrations.CreateModel(
            name='RvUsers',
            fields=[
                ('user_id', models.AutoField(serialize=False, primary_key=True)),
                ('contact_name', models.CharField(max_length=255)),
                ('email_address', models.CharField(max_length=64)),
                ('username', models.CharField(max_length=64, unique=True, null=True, blank=True)),
                ('password', models.CharField(max_length=64, null=True, blank=True)),
                ('language', models.CharField(max_length=5, null=True, blank=True)),
                ('default_account_id', models.IntegerField(null=True, blank=True)),
                ('comments', models.TextField(null=True, blank=True)),
                ('active', models.SmallIntegerField()),
                ('sso_user_id', models.IntegerField(unique=True, null=True, blank=True)),
                ('date_created', models.DateTimeField(null=True, blank=True)),
                ('date_last_login', models.DateTimeField(null=True, blank=True)),
                ('email_updated', models.DateTimeField(null=True, blank=True)),
            ],
            options={
                'db_table': 'rv_users',
            },
        ),
        migrations.CreateModel(
            name='RvVariablePublisher',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('variable_id', models.IntegerField()),
                ('publisher_id', models.IntegerField()),
                ('visible', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'rv_variable_publisher',
            },
        ),
        migrations.CreateModel(
            name='RvVariables',
            fields=[
                ('variableid', models.AutoField(serialize=False, primary_key=True)),
                ('trackerid', models.IntegerField()),
                ('name', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=250, null=True, blank=True)),
                ('datatype', models.TextField()),
                ('purpose', models.TextField(null=True, blank=True)),
                ('reject_if_empty', models.SmallIntegerField()),
                ('is_unique', models.IntegerField()),
                ('unique_window', models.IntegerField()),
                ('variablecode', models.CharField(max_length=255)),
                ('hidden', models.BooleanField()),
                ('updated', models.DateTimeField(null=True, blank=True)),
            ],
            options={
                'db_table': 'rv_variables',
            },
        ),
        migrations.CreateModel(
            name='RvZones',
            fields=[
                ('zoneid', models.AutoField(serialize=False, primary_key=True)),
                ('affiliateid', models.IntegerField(null=True, blank=True)),
                ('zonename', models.CharField(max_length=245)),
                ('description', models.CharField(max_length=255)),
                ('delivery', models.SmallIntegerField()),
                ('zonetype', models.SmallIntegerField()),
                ('category', models.TextField()),
                ('width', models.SmallIntegerField()),
                ('height', models.SmallIntegerField()),
                ('ad_selection', models.TextField()),
                ('chain', models.TextField()),
                ('prepend', models.TextField()),
                ('append', models.TextField()),
                ('appendtype', models.SmallIntegerField()),
                ('forceappend', models.NullBooleanField()),
                ('inventory_forecast_type', models.SmallIntegerField()),
                ('comments', models.TextField(null=True, blank=True)),
                ('cost', models.DecimalField(null=True, max_digits=10, decimal_places=4, blank=True)),
                ('cost_type', models.SmallIntegerField(null=True, blank=True)),
                ('cost_variable_id', models.CharField(max_length=255, null=True, blank=True)),
                ('technology_cost', models.DecimalField(null=True, max_digits=10, decimal_places=4, blank=True)),
                ('technology_cost_type', models.SmallIntegerField(null=True, blank=True)),
                ('updated', models.DateTimeField(null=True, blank=True)),
                ('block', models.IntegerField()),
                ('capping', models.IntegerField()),
                ('session_capping', models.IntegerField()),
                ('what', models.TextField()),
                ('as_zone_id', models.IntegerField(null=True, blank=True)),
                ('is_in_ad_direct', models.SmallIntegerField()),
                ('rate', models.DecimalField(null=True, max_digits=19, decimal_places=2, blank=True)),
                ('pricing', models.CharField(max_length=50)),
                ('oac_category_id', models.IntegerField(null=True, blank=True)),
                ('ext_adselection', models.CharField(max_length=255, null=True, blank=True)),
                ('show_capped_no_cookie', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'rv_zones',
            },
        ),
        migrations.AlterUniqueTogether(
            name='rvvariablepublisher',
            unique_together=set([('variable_id', 'publisher_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='rvpasswordrecovery',
            unique_together=set([('user_type', 'user_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='rvdatarawtrackervariablevalue',
            unique_together=set([('server_raw_tracker_impression_id', 'server_raw_ip', 'tracker_variable_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='rvdatarawtrackerimpression',
            unique_together=set([('server_raw_tracker_impression_id', 'server_raw_ip')]),
        ),
        migrations.AlterUniqueTogether(
            name='rvaclschannel',
            unique_together=set([('channelid', 'executionorder')]),
        ),
        migrations.AlterUniqueTogether(
            name='rvacls',
            unique_together=set([('bannerid', 'executionorder')]),
        ),
        migrations.AlterUniqueTogether(
            name='rvaccountuserpermissionassoc',
            unique_together=set([('account_id', 'user_id', 'permission_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='rvaccountuserassoc',
            unique_together=set([('account_id', 'user_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='rvaccountpreferenceassoc',
            unique_together=set([('account_id', 'preference_id')]),
        ),
    ]
